### PR TITLE
Added setup.cfg and requirements-dev.txt

### PR DESCRIPTION
**Pull request by GGabriele**
Related to #6

### CODE REVIEW

**Comment by dbarrosop** [comment]
That was fast : )

Keep this on hold as things might slightly change as discussed here: napalm-automation/napalm-base#61

**Comment by dbarrosop** [comment]
+1

**Comment by GGabriele** [comment]
Reverting one change to avoid conflicts with #13

**Comment by ktbyers** [comment]
Duplicate with this PR https://github.com/napalm-automation/napalm-panos/pull/19

Sorry @GGabriele didn't see this until after I submitted other PR.

**Pull request closed without merging**
