### PR TITLE
Adding fixes for #45

### PR DESCRIPTION
**Pull request by gjim83**
Issue explained here https://github.com/napalm-automation/napalm-panos/issues/45

### CODE REVIEW

**Comment by gjim83** [comment]
Oops, that's odd, it worked on my local branch. Will have a look at those failures shortly.

**Comment by gjim83** [comment]
ugh, I hadn't updated napalm-base in a while in this VM, will post amendment later today

**Comment by gjim83** [comment]
There, the tests needed to be updated after the fixes for https://github.com/napalm-automation/napalm-base/issues/228 were pushed

**Comment by GGabriele** [comment]
Thanks again! @gjim83

**Pull request merged**
